export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All', emoji: '' },
  { id: 'health', label: 'Health', emoji: '💪' },
  { id: 'learning', label: 'Learning', emoji: '📚' },
  { id: 'wellness', label: 'Wellness', emoji: '🧘' },
  { id: 'productivity', label: 'Productivity', emoji: '⚡' },
];

export const PACT_TEMPLATES = [
  {
    id: 'exercise-3x',
    title: 'Exercise 3x/week',
    description: 'Get at least 30 minutes of exercise three times this week.',
    emoji: '💪',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '18:00',
  },
  {
    id: 'read-20min',
    title: 'Read 20 min/day',
    description: 'Read for at least 20 minutes every day. Any book counts!',
    emoji: '📚',
    category: 'learning',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '21:00',
  },
  {
    id: 'no-social-media',
    title: 'No social media before noon',
    description: 'Stay off social media until noon to protect your morning focus.',
    emoji: '🧠',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '12:00',
  },
  {
    id: 'meditate-10min',
    title: 'Meditate 10 min/day',
    description: 'Start the day with a 10-minute meditation session.',
    emoji: '🧘',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '08:00',
  },
  {
    id: 'study-1hr',
    title: 'Study for 1 hour',
    description: 'Dedicate one focused hour to studying every day.',
    emoji: '📖',
    category: 'learning',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '20:00',
  },
  {
    id: 'drink-water',
    title: 'Drink 8 glasses of water',
    description: 'Stay hydrated! Track your water intake throughout the day.',
    emoji: '💧',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },
  {
    id: 'focused-work-30min',
    title: '30 min focused work',
    description: 'Complete at least 30 minutes of deep, distraction-free work.',
    emoji: '⚡',
    category: 'productivity',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '17:00',
  },
  {
    id: 'journal-before-bed',
    title: 'Journal before bed',
    description: 'Write in your journal before going to sleep. Reflect on the day.',
    emoji: '✍️',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },
];
