export const TEMPLATE_CATEGORIES = [
  { id: 'academics', label: 'Academics', emoji: '📚' },
  { id: 'health', label: 'Health', emoji: '💪' },
  { id: 'digital', label: 'Digital', emoji: '🧠' },
  { id: 'career', label: 'Career', emoji: '🚀' },
  { id: 'wellness', label: 'Wellness', emoji: '🧘' },
];

export const PACT_TEMPLATES = [
  // Academics
  {
    id: 'study-2hr',
    title: 'Study for 2 hours',
    description: 'Complete 2 focused hours of studying. No phone, no distractions.',
    emoji: '📚',
    category: 'academics',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '20:00',
  },
  {
    id: 'finish-assignment',
    title: 'Finish assignment tonight',
    description: 'Complete and submit your assignment before the deadline.',
    emoji: '📝',
    category: 'academics',
    isRecurring: false,
    recurrenceType: null,
    suggestedTime: '23:59',
  },
  {
    id: 'review-notes',
    title: 'Review lecture notes',
    description: 'Review today\'s lecture notes within 24 hours while they\'re fresh.',
    emoji: '📖',
    category: 'academics',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '22:00',
  },
  {
    id: 'read-30pages',
    title: 'Read 30 pages',
    description: 'Read 30 pages of your textbook or assigned reading.',
    emoji: '📕',
    category: 'academics',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },

  // Health & Fitness
  {
    id: 'workout-30min',
    title: 'Work out for 30 min',
    description: 'Get 30 minutes of exercise — gym, run, sport, yoga, anything counts.',
    emoji: '💪',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '20:00',
  },
  {
    id: 'sleep-by-midnight',
    title: 'Sleep by midnight',
    description: 'Be in bed with phone away by midnight.',
    emoji: '😴',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '23:55',
  },
  {
    id: 'drink-water',
    title: 'Drink 8 glasses of water',
    description: 'Stay hydrated! Track your water intake throughout the day.',
    emoji: '💧',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },
  {
    id: 'eat-real-meal',
    title: 'Eat a real meal',
    description: 'Eat at least one balanced meal today — not just snacks or junk food.',
    emoji: '🥗',
    category: 'health',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '20:00',
  },

  // Digital Wellness
  {
    id: 'no-phone-first-hour',
    title: 'No phone for first hour',
    description: 'Don\'t check your phone for the first hour after waking up.',
    emoji: '📵',
    category: 'digital',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '09:00',
  },
  {
    id: 'no-social-til-noon',
    title: 'No social media til noon',
    description: 'Stay off social media until noon to protect your morning focus.',
    emoji: '🧠',
    category: 'digital',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '12:00',
  },
  {
    id: 'screen-time-under-3h',
    title: 'Screen time under 3 hours',
    description: 'Keep your total recreational screen time under 3 hours today.',
    emoji: '⏱️',
    category: 'digital',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '23:00',
  },
  {
    id: 'no-phone-in-bed',
    title: 'No phone in bed',
    description: 'Charge phone outside bedroom. No scrolling in bed.',
    emoji: '🛏️',
    category: 'digital',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '23:00',
  },

  // Career & Skills
  {
    id: 'code-1hr',
    title: 'Code for 1 hour',
    description: 'Spend 1 hour writing code on a personal project or coursework.',
    emoji: '💻',
    category: 'career',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '22:00',
  },
  {
    id: 'apply-job',
    title: 'Apply to 1 job/internship',
    description: 'Submit at least one job or internship application today.',
    emoji: '🚀',
    category: 'career',
    isRecurring: true,
    recurrenceType: 'weekdays',
    suggestedTime: '18:00',
  },
  {
    id: 'learn-30min',
    title: 'Learn something new 30 min',
    description: 'Watch a tutorial, take a course module, or read industry content.',
    emoji: '🎓',
    category: 'career',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '21:00',
  },
  {
    id: 'work-on-portfolio',
    title: 'Work on portfolio',
    description: 'Spend 30 minutes updating or building your portfolio.',
    emoji: '💼',
    category: 'career',
    isRecurring: true,
    recurrenceType: 'weekly',
    suggestedTime: '20:00',
  },

  // Wellness
  {
    id: 'meditate-10min',
    title: 'Meditate for 10 min',
    description: 'Start or end your day with a 10-minute meditation session.',
    emoji: '🧘',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '08:00',
  },
  {
    id: 'journal',
    title: 'Journal before bed',
    description: 'Write in your journal before going to sleep. Reflect on the day.',
    emoji: '✍️',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },
  {
    id: 'go-outside',
    title: 'Get outside for 15 min',
    description: 'Spend at least 15 minutes outside, no phone. Fresh air and sunshine.',
    emoji: '🌿',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '18:00',
  },
  {
    id: 'gratitude',
    title: 'Write 3 things grateful for',
    description: 'Write down 3 things you\'re grateful for today.',
    emoji: '🙏',
    category: 'wellness',
    isRecurring: true,
    recurrenceType: 'daily',
    suggestedTime: '22:00',
  },
];
